#############################################################################
# Makefile for building: GlobalOptimus
# Generated by qmake (3.1) (Qt 5.15.8)
# Project:  GlobalOptimus.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile GlobalOptimus.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = GlobalOptimus1.0.0
DISTDIR = /home/sheridan/Desktop/ERGASIES/GlobalOptimus/.tmp/GlobalOptimus1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Core.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = LINESEARCH/armijosearch.cpp \
		LINESEARCH/fibonaccisearch.cpp \
		LINESEARCH/goldensearch.cpp \
		METHODS/bfgs.cpp \
		METHODS/differentialevolution.cpp \
		METHODS/genetic.cpp \
		METHODS/gradientdescent.cpp \
		LINESEARCH/linesearch.cpp \
		METHODS/multistart.cpp \
		OPTIMUS/statistics.cpp \
		OPTIMUS/collection.cpp \
		OPTIMUS/doublebox.cpp \
		OPTIMUS/similarity.cpp \
		PROBLEMS/bf1.cpp \
		PROBLEMS/bf2.cpp \
		PROBLEMS/branin.cpp \
		PROBLEMS/camel.cpp \
		PROBLEMS/cm.cpp \
		PROBLEMS/diffpower.cpp \
		PROBLEMS/easom.cpp \
		PROBLEMS/elp.cpp \
		PROBLEMS/exp.cpp \
		PROBLEMS/gkls.cpp \
		PROBLEMS/gkls250.cpp \
		main.cpp \
		OPTIMUS/optimizer.cpp \
		OPTIMUS/parameter.cpp \
		OPTIMUS/problem.cpp \
		PROBLEMS/rastriginproblem.cpp \
		PROBLEMS/test2nproblem.cpp 
OBJECTS       = armijosearch.o \
		fibonaccisearch.o \
		goldensearch.o \
		bfgs.o \
		differentialevolution.o \
		genetic.o \
		gradientdescent.o \
		linesearch.o \
		multistart.o \
		statistics.o \
		collection.o \
		doublebox.o \
		similarity.o \
		bf1.o \
		bf2.o \
		branin.o \
		camel.o \
		cm.o \
		diffpower.o \
		easom.o \
		elp.o \
		exp.o \
		gkls.o \
		gkls250.o \
		main.o \
		optimizer.o \
		parameter.o \
		problem.o \
		rastriginproblem.o \
		test2nproblem.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		GlobalOptimus.pro LINESEARCH/armijosearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/linesearch.h \
		METHODS/bfgs.h \
		METHODS/differentialevolution.h \
		METHODS/genetic.h \
		METHODS/gradientdescent.h \
		METHODS/multistart.h \
		OPTIMUS/statistics.h \
		OPTIMUS/collection.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/problem.h \
		OPTIMUS/similarity.h \
		PROBLEMS/bf1.h \
		PROBLEMS/bf2.h \
		PROBLEMS/branin.h \
		PROBLEMS/camel.h \
		PROBLEMS/cm.h \
		PROBLEMS/diffpower.h \
		PROBLEMS/easom.h \
		PROBLEMS/elp.h \
		PROBLEMS/exp.h \
		PROBLEMS/gkls.h \
		PROBLEMS/gkls250.h \
		PROBLEMS/rastriginproblem.h \
		PROBLEMS/test2nproblem.h LINESEARCH/armijosearch.cpp \
		LINESEARCH/fibonaccisearch.cpp \
		LINESEARCH/goldensearch.cpp \
		METHODS/bfgs.cpp \
		METHODS/differentialevolution.cpp \
		METHODS/genetic.cpp \
		METHODS/gradientdescent.cpp \
		LINESEARCH/linesearch.cpp \
		METHODS/multistart.cpp \
		OPTIMUS/statistics.cpp \
		OPTIMUS/collection.cpp \
		OPTIMUS/doublebox.cpp \
		OPTIMUS/similarity.cpp \
		PROBLEMS/bf1.cpp \
		PROBLEMS/bf2.cpp \
		PROBLEMS/branin.cpp \
		PROBLEMS/camel.cpp \
		PROBLEMS/cm.cpp \
		PROBLEMS/diffpower.cpp \
		PROBLEMS/easom.cpp \
		PROBLEMS/elp.cpp \
		PROBLEMS/exp.cpp \
		PROBLEMS/gkls.cpp \
		PROBLEMS/gkls250.cpp \
		main.cpp \
		OPTIMUS/optimizer.cpp \
		OPTIMUS/parameter.cpp \
		OPTIMUS/problem.cpp \
		PROBLEMS/rastriginproblem.cpp \
		PROBLEMS/test2nproblem.cpp
QMAKE_TARGET  = GlobalOptimus
DESTDIR       = 
TARGET        = GlobalOptimus


first: all
####### Build rules

GlobalOptimus:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GlobalOptimus.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		GlobalOptimus.pro
	$(QMAKE) -o Makefile GlobalOptimus.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
GlobalOptimus.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile GlobalOptimus.pro

qmake_all: FORCE


all: Makefile GlobalOptimus

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents LINESEARCH/armijosearch.h LINESEARCH/fibonaccisearch.h LINESEARCH/goldensearch.h LINESEARCH/linesearch.h METHODS/bfgs.h METHODS/differentialevolution.h METHODS/genetic.h METHODS/gradientdescent.h METHODS/multistart.h OPTIMUS/statistics.h OPTIMUS/collection.h OPTIMUS/doublebox.h OPTIMUS/optimizer.h OPTIMUS/parameter.h OPTIMUS/problem.h OPTIMUS/similarity.h PROBLEMS/bf1.h PROBLEMS/bf2.h PROBLEMS/branin.h PROBLEMS/camel.h PROBLEMS/cm.h PROBLEMS/diffpower.h PROBLEMS/easom.h PROBLEMS/elp.h PROBLEMS/exp.h PROBLEMS/gkls.h PROBLEMS/gkls250.h PROBLEMS/rastriginproblem.h PROBLEMS/test2nproblem.h $(DISTDIR)/
	$(COPY_FILE) --parents LINESEARCH/armijosearch.cpp LINESEARCH/fibonaccisearch.cpp LINESEARCH/goldensearch.cpp METHODS/bfgs.cpp METHODS/differentialevolution.cpp METHODS/genetic.cpp METHODS/gradientdescent.cpp LINESEARCH/linesearch.cpp METHODS/multistart.cpp OPTIMUS/statistics.cpp OPTIMUS/collection.cpp OPTIMUS/doublebox.cpp OPTIMUS/similarity.cpp PROBLEMS/bf1.cpp PROBLEMS/bf2.cpp PROBLEMS/branin.cpp PROBLEMS/camel.cpp PROBLEMS/cm.cpp PROBLEMS/diffpower.cpp PROBLEMS/easom.cpp PROBLEMS/elp.cpp PROBLEMS/exp.cpp PROBLEMS/gkls.cpp PROBLEMS/gkls250.cpp main.cpp OPTIMUS/optimizer.cpp OPTIMUS/parameter.cpp OPTIMUS/problem.cpp PROBLEMS/rastriginproblem.cpp PROBLEMS/test2nproblem.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

armijosearch.o: LINESEARCH/armijosearch.cpp LINESEARCH/armijosearch.h \
		LINESEARCH/linesearch.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armijosearch.o LINESEARCH/armijosearch.cpp

fibonaccisearch.o: LINESEARCH/fibonaccisearch.cpp LINESEARCH/fibonaccisearch.h \
		LINESEARCH/linesearch.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fibonaccisearch.o LINESEARCH/fibonaccisearch.cpp

goldensearch.o: LINESEARCH/goldensearch.cpp LINESEARCH/goldensearch.h \
		LINESEARCH/linesearch.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o goldensearch.o LINESEARCH/goldensearch.cpp

bfgs.o: METHODS/bfgs.cpp METHODS/bfgs.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bfgs.o METHODS/bfgs.cpp

differentialevolution.o: METHODS/differentialevolution.cpp METHODS/differentialevolution.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o differentialevolution.o METHODS/differentialevolution.cpp

genetic.o: METHODS/genetic.cpp METHODS/genetic.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o genetic.o METHODS/genetic.cpp

gradientdescent.o: METHODS/gradientdescent.cpp METHODS/gradientdescent.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/armijosearch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gradientdescent.o METHODS/gradientdescent.cpp

linesearch.o: LINESEARCH/linesearch.cpp LINESEARCH/linesearch.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linesearch.o LINESEARCH/linesearch.cpp

multistart.o: METHODS/multistart.cpp METHODS/multistart.h \
		OPTIMUS/problem.h \
		OPTIMUS/collection.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multistart.o METHODS/multistart.cpp

statistics.o: OPTIMUS/statistics.cpp OPTIMUS/statistics.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statistics.o OPTIMUS/statistics.cpp

collection.o: OPTIMUS/collection.cpp OPTIMUS/collection.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o collection.o OPTIMUS/collection.cpp

doublebox.o: OPTIMUS/doublebox.cpp OPTIMUS/doublebox.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doublebox.o OPTIMUS/doublebox.cpp

similarity.o: OPTIMUS/similarity.cpp OPTIMUS/similarity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o similarity.o OPTIMUS/similarity.cpp

bf1.o: PROBLEMS/bf1.cpp PROBLEMS/bf1.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bf1.o PROBLEMS/bf1.cpp

bf2.o: PROBLEMS/bf2.cpp PROBLEMS/bf2.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bf2.o PROBLEMS/bf2.cpp

branin.o: PROBLEMS/branin.cpp PROBLEMS/branin.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o branin.o PROBLEMS/branin.cpp

camel.o: PROBLEMS/camel.cpp PROBLEMS/camel.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camel.o PROBLEMS/camel.cpp

cm.o: PROBLEMS/cm.cpp PROBLEMS/cm.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cm.o PROBLEMS/cm.cpp

diffpower.o: PROBLEMS/diffpower.cpp PROBLEMS/diffpower.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diffpower.o PROBLEMS/diffpower.cpp

easom.o: PROBLEMS/easom.cpp PROBLEMS/easom.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o easom.o PROBLEMS/easom.cpp

elp.o: PROBLEMS/elp.cpp PROBLEMS/elp.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o elp.o PROBLEMS/elp.cpp

exp.o: PROBLEMS/exp.cpp PROBLEMS/exp.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exp.o PROBLEMS/exp.cpp

gkls.o: PROBLEMS/gkls.cpp PROBLEMS/gkls.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gkls.o PROBLEMS/gkls.cpp

gkls250.o: PROBLEMS/gkls250.cpp PROBLEMS/gkls250.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gkls250.o PROBLEMS/gkls250.cpp

main.o: main.cpp PROBLEMS/rastriginproblem.h \
		OPTIMUS/problem.h \
		PROBLEMS/test2nproblem.h \
		PROBLEMS/bf1.h \
		PROBLEMS/bf2.h \
		PROBLEMS/branin.h \
		PROBLEMS/camel.h \
		PROBLEMS/cm.h \
		PROBLEMS/diffpower.h \
		PROBLEMS/easom.h \
		PROBLEMS/elp.h \
		PROBLEMS/exp.h \
		METHODS/gradientdescent.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/armijosearch.h \
		METHODS/multistart.h \
		OPTIMUS/collection.h \
		METHODS/genetic.h \
		METHODS/bfgs.h \
		METHODS/differentialevolution.h \
		OPTIMUS/statistics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

optimizer.o: OPTIMUS/optimizer.cpp OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		METHODS/gradientdescent.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/armijosearch.h \
		METHODS/bfgs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optimizer.o OPTIMUS/optimizer.cpp

parameter.o: OPTIMUS/parameter.cpp OPTIMUS/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameter.o OPTIMUS/parameter.cpp

problem.o: OPTIMUS/problem.cpp OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o problem.o OPTIMUS/problem.cpp

rastriginproblem.o: PROBLEMS/rastriginproblem.cpp PROBLEMS/rastriginproblem.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rastriginproblem.o PROBLEMS/rastriginproblem.cpp

test2nproblem.o: PROBLEMS/test2nproblem.cpp PROBLEMS/test2nproblem.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test2nproblem.o PROBLEMS/test2nproblem.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/GlobalOptimus/bin || mkdir -p $(INSTALL_ROOT)/opt/GlobalOptimus/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/GlobalOptimus/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/GlobalOptimus/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/GlobalOptimus/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/GlobalOptimus/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

