#############################################################################
# Makefile for building: DataFitting
# Generated by qmake (3.1) (Qt 5.15.8)
# Project:  DataFitting.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile DataFitting.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O3 -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -O2 -O3 -march=native -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O3 -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -O2 -O3 -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = DataFitting1.0.0
DISTDIR = /home/sheridan/Desktop/ERGASIES/GlobalOptimus/.tmp/DataFitting1.0.0
LINK          = g++
LFLAGS        = -O3 -Wl,-O1
LIBS          = $(SUBLIBS) -lm -fopenmp /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = GE/cprogram.cc \
		METHODS/eo.cpp \
		GE/doublestack.cc \
		GE/fcprogram.cpp \
		GE/fparser.cc \
		GE/fpoptimizer.cc \
		GE/mapper.cc \
		GE/population.cc \
		GE/program.cc \
		GE/rule.cc \
		GE/symbol.cc \
		GE/integeranneal.cpp \
		GE/nncprogram.cpp \
		GE/ruleprogram.cpp \
		METHODS/acop.cpp \
		METHODS/ego.cpp \
		METHODS/hybridmethod.cpp \
		METHODS/jDElsgo.cpp \
		METHODS/mbfgs.cpp \
		METHODS/mewoa.cpp \
		METHODS/saop.cpp \
		METHODS/woa.cpp \
		MLMODELS/airbf.cpp \
		MLMODELS/fcmodel.cpp \
		OPTIMUS/editlogger.cpp \
		OPTIMUS/filelogger.cpp \
		OPTIMUS/logger.cpp \
		OPTIMUS/mean.cpp \
		METHODS/gwooptimizer.cpp \
		METHODS/ofalgorithm.cpp \
		METHODS/adam.cpp \
		METHODS/armadillo1.cpp \
		METHODS/ipso.cpp \
		METHODS/lbfgs.cpp \
		METHODS/neldermead.cpp \
		METHODS/neuralminimizer.cpp \
		METHODS/parallelde.cpp \
		METHODS/parallelpso.cpp \
		METHODS/simanmethod.cpp \
		METHODS/usermethod.cpp \
		MLMODELS/gdfmodel.cpp \
		MLMODELS/nncmodel.cpp \
		MLMODELS/rulemodel.cpp \
		MLMODELS/mlpproblem.cpp \
		MLMODELS/model.cpp \
		LINESEARCH/armijosearch.cpp \
		LINESEARCH/fibonaccisearch.cpp \
		LINESEARCH/goldensearch.cpp \
		METHODS/bfgs.cpp \
		METHODS/differentialevolution.cpp \
		METHODS/genetic.cpp \
		METHODS/gradientdescent.cpp \
		LINESEARCH/linesearch.cpp \
		METHODS/multistart.cpp \
		MLMODELS/rbfproblem.cpp \
		OPTIMUS/methodloader.cpp \
		OPTIMUS/parameterlist.cpp \
		OPTIMUS/statistics.cpp \
		OPTIMUS/collection.cpp \
		OPTIMUS/doublebox.cpp \
		OPTIMUS/similarity.cpp \
		MLMODELS/dataset.cpp \
		SAMPLER/kmeanssampler.cpp \
		SAMPLER/maxwellsampler.cpp \
		SAMPLER/neuralsampler.cpp \
		SAMPLER/rbfsampler.cpp \
		SAMPLER/triangularsampler.cpp \
		SAMPLER/uniformsampler.cpp \
		datafitting.cpp \
		OPTIMUS/optimizer.cpp \
		OPTIMUS/parameter.cpp \
		OPTIMUS/problem.cpp \
		MLMODELS/converter.cc \
		MLMODELS/neuralparser.cc \
		SAMPLER/problemsampler.cpp 
OBJECTS       = cprogram.o \
		eo.o \
		doublestack.o \
		fcprogram.o \
		fparser.o \
		fpoptimizer.o \
		mapper.o \
		population.o \
		program.o \
		rule.o \
		symbol.o \
		integeranneal.o \
		nncprogram.o \
		ruleprogram.o \
		acop.o \
		ego.o \
		hybridmethod.o \
		jDElsgo.o \
		mbfgs.o \
		mewoa.o \
		saop.o \
		woa.o \
		airbf.o \
		fcmodel.o \
		editlogger.o \
		filelogger.o \
		logger.o \
		mean.o \
		gwooptimizer.o \
		ofalgorithm.o \
		adam.o \
		armadillo1.o \
		ipso.o \
		lbfgs.o \
		neldermead.o \
		neuralminimizer.o \
		parallelde.o \
		parallelpso.o \
		simanmethod.o \
		usermethod.o \
		gdfmodel.o \
		nncmodel.o \
		rulemodel.o \
		mlpproblem.o \
		model.o \
		armijosearch.o \
		fibonaccisearch.o \
		goldensearch.o \
		bfgs.o \
		differentialevolution.o \
		genetic.o \
		gradientdescent.o \
		linesearch.o \
		multistart.o \
		rbfproblem.o \
		methodloader.o \
		parameterlist.o \
		statistics.o \
		collection.o \
		doublebox.o \
		similarity.o \
		dataset.o \
		kmeanssampler.o \
		maxwellsampler.o \
		neuralsampler.o \
		rbfsampler.o \
		triangularsampler.o \
		uniformsampler.o \
		datafitting.o \
		optimizer.o \
		parameter.o \
		problem.o \
		converter.o \
		neuralparser.o \
		problemsampler.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		DataFitting.pro GE/cprogram.h \
		METHODS/eo.h \
		GE/doublestack.h \
		GE/fcprogram.h \
		GE/fparser.hh \
		GE/fpconfig.hh \
		GE/fptypes.hh \
		GE/mapper.h \
		GE/population.h \
		GE/program.h \
		GE/rule.h \
		GE/symbol.h \
		METHODS/eo.h \
		METHODS/acop.h \
		METHODS/ego.h \
		METHODS/hybridmethod.h \
		METHODS/jDElsgo.h \
		METHODS/mbfgs.h \
		METHODS/mewoa.h \
		METHODS/saop.h \
		METHODS/woa.h \
		MLMODELS/airbf.h \
		MLMODELS/fcmodel.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/logger.h \
		OPTIMUS/mean.h \
		OPTIMUS/methodloader.h \
		GE/integeranneal.h \
		GE/nncprogram.h \
		GE/ruleprogram.h \
		METHODS/adam.h \
		METHODS/gwooptimizer.h \
		METHODS/ipso.h \
		METHODS/lbfgs.h \
		METHODS/neldermead.h \
		METHODS/neuralminimizer.h \
		METHODS/parallelde.h \
		METHODS/parallelpso.h \
		METHODS/simanmethod.h \
		METHODS/ofalgorithm.h \
		METHODS/usermethod.h \
		METHODS/armadillo1.h \
		MLMODELS/gdfmodel.h \
		MLMODELS/rulemodel.h \
		MLMODELS/nncmodel.h \
		MLMODELS/mlpproblem.h \
		MLMODELS/model.h \
		LINESEARCH/armijosearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/linesearch.h \
		METHODS/bfgs.h \
		METHODS/differentialevolution.h \
		METHODS/genetic.h \
		METHODS/gradientdescent.h \
		METHODS/multistart.h \
		MLMODELS/rbfproblem.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/statistics.h \
		OPTIMUS/collection.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/problem.h \
		OPTIMUS/similarity.h \
		MLMODELS/dataset.h \
		SAMPLER/kmeanssampler.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/triangularsampler.h \
		MLMODELS/converter.h \
		MLMODELS/neuralparser.h \
		SAMPLER/uniformsampler.h GE/cprogram.cc \
		METHODS/eo.cpp \
		GE/doublestack.cc \
		GE/fcprogram.cpp \
		GE/fparser.cc \
		GE/fpoptimizer.cc \
		GE/mapper.cc \
		GE/population.cc \
		GE/program.cc \
		GE/rule.cc \
		GE/symbol.cc \
		GE/integeranneal.cpp \
		GE/nncprogram.cpp \
		GE/ruleprogram.cpp \
		METHODS/acop.cpp \
		METHODS/ego.cpp \
		METHODS/hybridmethod.cpp \
		METHODS/jDElsgo.cpp \
		METHODS/mbfgs.cpp \
		METHODS/mewoa.cpp \
		METHODS/saop.cpp \
		METHODS/woa.cpp \
		MLMODELS/airbf.cpp \
		MLMODELS/fcmodel.cpp \
		OPTIMUS/editlogger.cpp \
		OPTIMUS/filelogger.cpp \
		OPTIMUS/logger.cpp \
		OPTIMUS/mean.cpp \
		METHODS/gwooptimizer.cpp \
		METHODS/ofalgorithm.cpp \
		METHODS/adam.cpp \
		METHODS/armadillo1.cpp \
		METHODS/ipso.cpp \
		METHODS/lbfgs.cpp \
		METHODS/neldermead.cpp \
		METHODS/neuralminimizer.cpp \
		METHODS/parallelde.cpp \
		METHODS/parallelpso.cpp \
		METHODS/simanmethod.cpp \
		METHODS/usermethod.cpp \
		MLMODELS/gdfmodel.cpp \
		MLMODELS/nncmodel.cpp \
		MLMODELS/rulemodel.cpp \
		MLMODELS/mlpproblem.cpp \
		MLMODELS/model.cpp \
		LINESEARCH/armijosearch.cpp \
		LINESEARCH/fibonaccisearch.cpp \
		LINESEARCH/goldensearch.cpp \
		METHODS/bfgs.cpp \
		METHODS/differentialevolution.cpp \
		METHODS/genetic.cpp \
		METHODS/gradientdescent.cpp \
		LINESEARCH/linesearch.cpp \
		METHODS/multistart.cpp \
		MLMODELS/rbfproblem.cpp \
		OPTIMUS/methodloader.cpp \
		OPTIMUS/parameterlist.cpp \
		OPTIMUS/statistics.cpp \
		OPTIMUS/collection.cpp \
		OPTIMUS/doublebox.cpp \
		OPTIMUS/similarity.cpp \
		MLMODELS/dataset.cpp \
		SAMPLER/kmeanssampler.cpp \
		SAMPLER/maxwellsampler.cpp \
		SAMPLER/neuralsampler.cpp \
		SAMPLER/rbfsampler.cpp \
		SAMPLER/triangularsampler.cpp \
		SAMPLER/uniformsampler.cpp \
		datafitting.cpp \
		OPTIMUS/optimizer.cpp \
		OPTIMUS/parameter.cpp \
		OPTIMUS/problem.cpp \
		MLMODELS/converter.cc \
		MLMODELS/neuralparser.cc \
		SAMPLER/problemsampler.cpp
QMAKE_TARGET  = DataFitting
DESTDIR       = 
TARGET        = DataFitting


first: all
####### Build rules

DataFitting:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DataFitting.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		DataFitting.pro
	$(QMAKE) -o Makefile DataFitting.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
DataFitting.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile DataFitting.pro

qmake_all: FORCE


all: Makefile DataFitting

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents GE/cprogram.h METHODS/eo.h GE/doublestack.h GE/fcprogram.h GE/fparser.hh GE/fpconfig.hh GE/fptypes.hh GE/mapper.h GE/population.h GE/program.h GE/rule.h GE/symbol.h METHODS/eo.h METHODS/acop.h METHODS/ego.h METHODS/hybridmethod.h METHODS/jDElsgo.h METHODS/mbfgs.h METHODS/mewoa.h METHODS/saop.h METHODS/woa.h MLMODELS/airbf.h MLMODELS/fcmodel.h OPTIMUS/editlogger.h OPTIMUS/filelogger.h OPTIMUS/logger.h OPTIMUS/mean.h OPTIMUS/methodloader.h GE/integeranneal.h GE/nncprogram.h GE/ruleprogram.h METHODS/adam.h METHODS/gwooptimizer.h METHODS/ipso.h METHODS/lbfgs.h METHODS/neldermead.h METHODS/neuralminimizer.h METHODS/parallelde.h METHODS/parallelpso.h METHODS/simanmethod.h METHODS/ofalgorithm.h METHODS/usermethod.h METHODS/armadillo1.h MLMODELS/gdfmodel.h MLMODELS/rulemodel.h MLMODELS/nncmodel.h MLMODELS/mlpproblem.h MLMODELS/model.h LINESEARCH/armijosearch.h LINESEARCH/fibonaccisearch.h LINESEARCH/goldensearch.h LINESEARCH/linesearch.h METHODS/bfgs.h METHODS/differentialevolution.h METHODS/genetic.h METHODS/gradientdescent.h METHODS/multistart.h MLMODELS/rbfproblem.h OPTIMUS/parameterlist.h OPTIMUS/statistics.h OPTIMUS/collection.h OPTIMUS/doublebox.h OPTIMUS/optimizer.h OPTIMUS/parameter.h OPTIMUS/problem.h OPTIMUS/similarity.h MLMODELS/dataset.h SAMPLER/kmeanssampler.h SAMPLER/maxwellsampler.h SAMPLER/neuralsampler.h SAMPLER/problemsampler.h SAMPLER/rbfsampler.h SAMPLER/triangularsampler.h MLMODELS/converter.h MLMODELS/neuralparser.h SAMPLER/uniformsampler.h $(DISTDIR)/
	$(COPY_FILE) --parents GE/cprogram.cc METHODS/eo.cpp GE/doublestack.cc GE/fcprogram.cpp GE/fparser.cc GE/fpoptimizer.cc GE/mapper.cc GE/population.cc GE/program.cc GE/rule.cc GE/symbol.cc GE/integeranneal.cpp GE/nncprogram.cpp GE/ruleprogram.cpp METHODS/acop.cpp METHODS/ego.cpp METHODS/hybridmethod.cpp METHODS/jDElsgo.cpp METHODS/mbfgs.cpp METHODS/mewoa.cpp METHODS/saop.cpp METHODS/woa.cpp MLMODELS/airbf.cpp MLMODELS/fcmodel.cpp OPTIMUS/editlogger.cpp OPTIMUS/filelogger.cpp OPTIMUS/logger.cpp OPTIMUS/mean.cpp METHODS/gwooptimizer.cpp METHODS/ofalgorithm.cpp METHODS/adam.cpp METHODS/armadillo1.cpp METHODS/ipso.cpp METHODS/lbfgs.cpp METHODS/neldermead.cpp METHODS/neuralminimizer.cpp METHODS/parallelde.cpp METHODS/parallelpso.cpp METHODS/simanmethod.cpp METHODS/usermethod.cpp MLMODELS/gdfmodel.cpp MLMODELS/nncmodel.cpp MLMODELS/rulemodel.cpp MLMODELS/mlpproblem.cpp MLMODELS/model.cpp LINESEARCH/armijosearch.cpp LINESEARCH/fibonaccisearch.cpp LINESEARCH/goldensearch.cpp METHODS/bfgs.cpp METHODS/differentialevolution.cpp METHODS/genetic.cpp METHODS/gradientdescent.cpp LINESEARCH/linesearch.cpp METHODS/multistart.cpp MLMODELS/rbfproblem.cpp OPTIMUS/methodloader.cpp OPTIMUS/parameterlist.cpp OPTIMUS/statistics.cpp OPTIMUS/collection.cpp OPTIMUS/doublebox.cpp OPTIMUS/similarity.cpp MLMODELS/dataset.cpp SAMPLER/kmeanssampler.cpp SAMPLER/maxwellsampler.cpp SAMPLER/neuralsampler.cpp SAMPLER/rbfsampler.cpp SAMPLER/triangularsampler.cpp SAMPLER/uniformsampler.cpp datafitting.cpp OPTIMUS/optimizer.cpp OPTIMUS/parameter.cpp OPTIMUS/problem.cpp MLMODELS/converter.cc MLMODELS/neuralparser.cc SAMPLER/problemsampler.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O3 -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -O2 -O3 -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

cprogram.o: GE/cprogram.cc GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		GE/program.h \
		MLMODELS/model.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cprogram.o GE/cprogram.cc

eo.o: METHODS/eo.cpp METHODS/eo.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eo.o METHODS/eo.cpp

doublestack.o: GE/doublestack.cc GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doublestack.o GE/doublestack.cc

fcprogram.o: GE/fcprogram.cpp GE/fcprogram.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		GE/program.h \
		MLMODELS/model.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		GE/mapper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fcprogram.o GE/fcprogram.cpp

fparser.o: GE/fparser.cc GE/fparser.hh \
		GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fparser.o GE/fparser.cc

fpoptimizer.o: GE/fpoptimizer.cc GE/fpconfig.hh \
		GE/fparser.hh \
		GE/fptypes.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fpoptimizer.o GE/fpoptimizer.cc

mapper.o: GE/mapper.cc GE/mapper.h \
		GE/fparser.hh \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapper.o GE/mapper.cc

population.o: GE/population.cc GE/population.h \
		GE/program.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		OPTIMUS/problem.h \
		METHODS/bfgs.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h \
		METHODS/simanmethod.h \
		OPTIMUS/collection.h \
		GE/integeranneal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o population.o GE/population.cc

program.o: GE/program.cc GE/program.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o program.o GE/program.cc

rule.o: GE/rule.cc GE/rule.h \
		GE/symbol.h \
		GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rule.o GE/rule.cc

symbol.o: GE/symbol.cc GE/symbol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o symbol.o GE/symbol.cc

integeranneal.o: GE/integeranneal.cpp GE/integeranneal.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h \
		GE/program.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integeranneal.o GE/integeranneal.cpp

nncprogram.o: GE/nncprogram.cpp GE/nncprogram.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		GE/program.h \
		MLMODELS/model.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nncprogram.o GE/nncprogram.cpp

ruleprogram.o: GE/ruleprogram.cpp GE/ruleprogram.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		GE/program.h \
		MLMODELS/model.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ruleprogram.o GE/ruleprogram.cpp

acop.o: METHODS/acop.cpp METHODS/acop.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o acop.o METHODS/acop.cpp

ego.o: METHODS/ego.cpp METHODS/ego.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h \
		METHODS/gradientdescent.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/armijosearch.h \
		METHODS/bfgs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ego.o METHODS/ego.cpp

hybridmethod.o: METHODS/hybridmethod.cpp METHODS/hybridmethod.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hybridmethod.o METHODS/hybridmethod.cpp

jDElsgo.o: METHODS/jDElsgo.cpp METHODS/jDElsgo.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jDElsgo.o METHODS/jDElsgo.cpp

mbfgs.o: METHODS/mbfgs.cpp METHODS/mbfgs.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mbfgs.o METHODS/mbfgs.cpp

mewoa.o: METHODS/mewoa.cpp METHODS/mewoa.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mewoa.o METHODS/mewoa.cpp

saop.o: METHODS/saop.cpp METHODS/saop.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o saop.o METHODS/saop.cpp

woa.o: METHODS/woa.cpp METHODS/woa.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o woa.o METHODS/woa.cpp

airbf.o: MLMODELS/airbf.cpp MLMODELS/airbf.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		MLMODELS/model.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o airbf.o MLMODELS/airbf.cpp

fcmodel.o: MLMODELS/fcmodel.cpp MLMODELS/fcmodel.h \
		MLMODELS/model.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		GE/program.h \
		GE/population.h \
		OPTIMUS/methodloader.h \
		METHODS/gradientdescent.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/armijosearch.h \
		METHODS/multistart.h \
		OPTIMUS/collection.h \
		METHODS/genetic.h \
		METHODS/bfgs.h \
		METHODS/lbfgs.h \
		METHODS/differentialevolution.h \
		METHODS/ipso.h \
		METHODS/neuralminimizer.h \
		METHODS/parallelde.h \
		METHODS/parallelpso.h \
		METHODS/neldermead.h \
		METHODS/adam.h \
		METHODS/armadillo1.h \
		METHODS/simanmethod.h \
		METHODS/usermethod.h \
		METHODS/ofalgorithm.h \
		METHODS/gwooptimizer.h \
		METHODS/ego.h \
		METHODS/hybridmethod.h \
		METHODS/woa.h \
		METHODS/mewoa.h \
		METHODS/jDElsgo.h \
		METHODS/saop.h \
		METHODS/acop.h \
		METHODS/eo.h \
		METHODS/mbfgs.h \
		GE/fcprogram.h \
		GE/mapper.h \
		MLMODELS/mlpproblem.h \
		MLMODELS/rbfproblem.h \
		MLMODELS/nncmodel.h \
		GE/nncprogram.h \
		MLMODELS/neuralparser.h \
		MLMODELS/converter.h \
		MLMODELS/gdfmodel.h \
		MLMODELS/rulemodel.h \
		GE/ruleprogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fcmodel.o MLMODELS/fcmodel.cpp

editlogger.o: OPTIMUS/editlogger.cpp OPTIMUS/editlogger.h \
		OPTIMUS/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editlogger.o OPTIMUS/editlogger.cpp

filelogger.o: OPTIMUS/filelogger.cpp OPTIMUS/filelogger.h \
		OPTIMUS/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filelogger.o OPTIMUS/filelogger.cpp

logger.o: OPTIMUS/logger.cpp OPTIMUS/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o OPTIMUS/logger.cpp

mean.o: OPTIMUS/mean.cpp OPTIMUS/mean.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mean.o OPTIMUS/mean.cpp

gwooptimizer.o: METHODS/gwooptimizer.cpp METHODS/gwooptimizer.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gwooptimizer.o METHODS/gwooptimizer.cpp

ofalgorithm.o: METHODS/ofalgorithm.cpp METHODS/ofalgorithm.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h \
		METHODS/gradientdescent.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/armijosearch.h \
		METHODS/bfgs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ofalgorithm.o METHODS/ofalgorithm.cpp

adam.o: METHODS/adam.cpp METHODS/adam.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/armijosearch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adam.o METHODS/adam.cpp

armadillo1.o: METHODS/armadillo1.cpp METHODS/armadillo1.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armadillo1.o METHODS/armadillo1.cpp

ipso.o: METHODS/ipso.cpp METHODS/ipso.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ipso.o METHODS/ipso.cpp

lbfgs.o: METHODS/lbfgs.cpp METHODS/lbfgs.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lbfgs.o METHODS/lbfgs.cpp

neldermead.o: METHODS/neldermead.cpp METHODS/neldermead.h \
		OPTIMUS/problem.h \
		OPTIMUS/collection.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neldermead.o METHODS/neldermead.cpp

neuralminimizer.o: METHODS/neuralminimizer.cpp METHODS/neuralminimizer.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neuralminimizer.o METHODS/neuralminimizer.cpp

parallelde.o: METHODS/parallelde.cpp METHODS/parallelde.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parallelde.o METHODS/parallelde.cpp

parallelpso.o: METHODS/parallelpso.cpp METHODS/parallelpso.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parallelpso.o METHODS/parallelpso.cpp

simanmethod.o: METHODS/simanmethod.cpp METHODS/simanmethod.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simanmethod.o METHODS/simanmethod.cpp

usermethod.o: METHODS/usermethod.cpp METHODS/usermethod.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usermethod.o METHODS/usermethod.cpp

gdfmodel.o: MLMODELS/gdfmodel.cpp MLMODELS/gdfmodel.h \
		MLMODELS/model.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		GE/program.h \
		GE/population.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gdfmodel.o MLMODELS/gdfmodel.cpp

nncmodel.o: MLMODELS/nncmodel.cpp MLMODELS/nncmodel.h \
		MLMODELS/model.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		GE/nncprogram.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		GE/program.h \
		GE/population.h \
		MLMODELS/neuralparser.h \
		MLMODELS/mlpproblem.h \
		MLMODELS/converter.h \
		METHODS/bfgs.h \
		METHODS/lbfgs.h \
		METHODS/adam.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/armijosearch.h \
		METHODS/genetic.h \
		OPTIMUS/collection.h \
		METHODS/mbfgs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nncmodel.o MLMODELS/nncmodel.cpp

rulemodel.o: MLMODELS/rulemodel.cpp MLMODELS/rulemodel.h \
		MLMODELS/model.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		GE/nncprogram.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		GE/program.h \
		GE/population.h \
		MLMODELS/neuralparser.h \
		MLMODELS/mlpproblem.h \
		MLMODELS/converter.h \
		METHODS/bfgs.h \
		METHODS/lbfgs.h \
		METHODS/adam.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/armijosearch.h \
		METHODS/genetic.h \
		OPTIMUS/collection.h \
		GE/ruleprogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rulemodel.o MLMODELS/rulemodel.cpp

mlpproblem.o: MLMODELS/mlpproblem.cpp MLMODELS/mlpproblem.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		MLMODELS/model.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mlpproblem.o MLMODELS/mlpproblem.cpp

model.o: MLMODELS/model.cpp MLMODELS/model.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o MLMODELS/model.cpp

armijosearch.o: LINESEARCH/armijosearch.cpp LINESEARCH/armijosearch.h \
		LINESEARCH/linesearch.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armijosearch.o LINESEARCH/armijosearch.cpp

fibonaccisearch.o: LINESEARCH/fibonaccisearch.cpp LINESEARCH/fibonaccisearch.h \
		LINESEARCH/linesearch.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fibonaccisearch.o LINESEARCH/fibonaccisearch.cpp

goldensearch.o: LINESEARCH/goldensearch.cpp LINESEARCH/goldensearch.h \
		LINESEARCH/linesearch.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o goldensearch.o LINESEARCH/goldensearch.cpp

bfgs.o: METHODS/bfgs.cpp METHODS/bfgs.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bfgs.o METHODS/bfgs.cpp

differentialevolution.o: METHODS/differentialevolution.cpp METHODS/differentialevolution.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h \
		MLMODELS/mlpproblem.h \
		MLMODELS/model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o differentialevolution.o METHODS/differentialevolution.cpp

genetic.o: METHODS/genetic.cpp METHODS/genetic.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o genetic.o METHODS/genetic.cpp

gradientdescent.o: METHODS/gradientdescent.cpp METHODS/gradientdescent.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/armijosearch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gradientdescent.o METHODS/gradientdescent.cpp

linesearch.o: LINESEARCH/linesearch.cpp LINESEARCH/linesearch.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linesearch.o LINESEARCH/linesearch.cpp

multistart.o: METHODS/multistart.cpp METHODS/multistart.h \
		OPTIMUS/problem.h \
		OPTIMUS/collection.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multistart.o METHODS/multistart.cpp

rbfproblem.o: MLMODELS/rbfproblem.cpp MLMODELS/rbfproblem.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		MLMODELS/model.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rbfproblem.o MLMODELS/rbfproblem.cpp

methodloader.o: OPTIMUS/methodloader.cpp OPTIMUS/methodloader.h \
		METHODS/gradientdescent.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/armijosearch.h \
		METHODS/multistart.h \
		OPTIMUS/collection.h \
		METHODS/genetic.h \
		METHODS/bfgs.h \
		METHODS/lbfgs.h \
		METHODS/differentialevolution.h \
		METHODS/ipso.h \
		METHODS/neuralminimizer.h \
		METHODS/parallelde.h \
		METHODS/parallelpso.h \
		METHODS/neldermead.h \
		METHODS/adam.h \
		METHODS/armadillo1.h \
		METHODS/simanmethod.h \
		METHODS/usermethod.h \
		METHODS/ofalgorithm.h \
		METHODS/gwooptimizer.h \
		METHODS/ego.h \
		METHODS/hybridmethod.h \
		METHODS/woa.h \
		METHODS/mewoa.h \
		METHODS/jDElsgo.h \
		METHODS/saop.h \
		METHODS/acop.h \
		METHODS/eo.h \
		METHODS/mbfgs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o methodloader.o OPTIMUS/methodloader.cpp

parameterlist.o: OPTIMUS/parameterlist.cpp OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameterlist.o OPTIMUS/parameterlist.cpp

statistics.o: OPTIMUS/statistics.cpp OPTIMUS/statistics.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statistics.o OPTIMUS/statistics.cpp

collection.o: OPTIMUS/collection.cpp OPTIMUS/collection.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o collection.o OPTIMUS/collection.cpp

doublebox.o: OPTIMUS/doublebox.cpp OPTIMUS/doublebox.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doublebox.o OPTIMUS/doublebox.cpp

similarity.o: OPTIMUS/similarity.cpp OPTIMUS/similarity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o similarity.o OPTIMUS/similarity.cpp

dataset.o: MLMODELS/dataset.cpp MLMODELS/dataset.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dataset.o MLMODELS/dataset.cpp

kmeanssampler.o: SAMPLER/kmeanssampler.cpp SAMPLER/kmeanssampler.h \
		SAMPLER/problemsampler.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kmeanssampler.o SAMPLER/kmeanssampler.cpp

maxwellsampler.o: SAMPLER/maxwellsampler.cpp SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxwellsampler.o SAMPLER/maxwellsampler.cpp

neuralsampler.o: SAMPLER/neuralsampler.cpp SAMPLER/neuralsampler.h \
		SAMPLER/problemsampler.h \
		OPTIMUS/problem.h \
		MLMODELS/dataset.h \
		METHODS/bfgs.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h \
		METHODS/lbfgs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neuralsampler.o SAMPLER/neuralsampler.cpp

rbfsampler.o: SAMPLER/rbfsampler.cpp SAMPLER/rbfsampler.h \
		OPTIMUS/problem.h \
		SAMPLER/problemsampler.h \
		MLMODELS/dataset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rbfsampler.o SAMPLER/rbfsampler.cpp

triangularsampler.o: SAMPLER/triangularsampler.cpp SAMPLER/triangularsampler.h \
		SAMPLER/problemsampler.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o triangularsampler.o SAMPLER/triangularsampler.cpp

uniformsampler.o: SAMPLER/uniformsampler.cpp SAMPLER/uniformsampler.h \
		SAMPLER/problemsampler.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uniformsampler.o SAMPLER/uniformsampler.cpp

datafitting.o: datafitting.cpp MLMODELS/mlpproblem.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		MLMODELS/model.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		MLMODELS/rbfproblem.h \
		MLMODELS/gdfmodel.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		GE/program.h \
		GE/population.h \
		MLMODELS/nncmodel.h \
		GE/nncprogram.h \
		MLMODELS/neuralparser.h \
		MLMODELS/converter.h \
		METHODS/bfgs.h \
		METHODS/lbfgs.h \
		METHODS/adam.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/armijosearch.h \
		METHODS/genetic.h \
		OPTIMUS/collection.h \
		METHODS/mbfgs.h \
		MLMODELS/rulemodel.h \
		GE/ruleprogram.h \
		MLMODELS/fcmodel.h \
		OPTIMUS/methodloader.h \
		METHODS/gradientdescent.h \
		METHODS/multistart.h \
		METHODS/differentialevolution.h \
		METHODS/ipso.h \
		METHODS/neuralminimizer.h \
		METHODS/parallelde.h \
		METHODS/parallelpso.h \
		METHODS/neldermead.h \
		METHODS/armadillo1.h \
		METHODS/simanmethod.h \
		METHODS/usermethod.h \
		METHODS/ofalgorithm.h \
		METHODS/gwooptimizer.h \
		METHODS/ego.h \
		METHODS/hybridmethod.h \
		METHODS/woa.h \
		METHODS/mewoa.h \
		METHODS/jDElsgo.h \
		METHODS/saop.h \
		METHODS/acop.h \
		METHODS/eo.h \
		GE/fcprogram.h \
		GE/mapper.h \
		OPTIMUS/statistics.h \
		MLMODELS/functionalrbf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datafitting.o datafitting.cpp

optimizer.o: OPTIMUS/optimizer.cpp OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		OPTIMUS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		OPTIMUS/logger.h \
		OPTIMUS/filelogger.h \
		OPTIMUS/editlogger.h \
		OPTIMUS/parameterlist.h \
		METHODS/gradientdescent.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/armijosearch.h \
		METHODS/bfgs.h \
		METHODS/lbfgs.h \
		METHODS/neldermead.h \
		OPTIMUS/collection.h \
		METHODS/adam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optimizer.o OPTIMUS/optimizer.cpp

parameter.o: OPTIMUS/parameter.cpp OPTIMUS/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameter.o OPTIMUS/parameter.cpp

problem.o: OPTIMUS/problem.cpp OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o problem.o OPTIMUS/problem.cpp

converter.o: MLMODELS/converter.cc MLMODELS/converter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o converter.o MLMODELS/converter.cc

neuralparser.o: MLMODELS/neuralparser.cc MLMODELS/neuralparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neuralparser.o MLMODELS/neuralparser.cc

problemsampler.o: SAMPLER/problemsampler.cpp SAMPLER/problemsampler.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o problemsampler.o SAMPLER/problemsampler.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/DataFitting/bin || mkdir -p $(INSTALL_ROOT)/opt/DataFitting/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/DataFitting/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/DataFitting/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/DataFitting/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/DataFitting/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

