#############################################################################
# Makefile for building: GlobalOptimus
# Generated by qmake (3.1) (Qt 5.15.8)
# Project:  GlobalOptimus.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile GlobalOptimus.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -O3 -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -O2 -O3 -march=native -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O3 -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -O2 -O3 -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = GlobalOptimus1.0.0
DISTDIR = /home/sheridan/Desktop/ERGASIES/GlobalOptimus/.tmp/GlobalOptimus1.0.0
LINK          = g++
LFLAGS        = -O3 -Wl,-O1
LIBS          = $(SUBLIBS) -lm -fopenmp /usr/lib/x86_64-linux-gnu/libQt5Core.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = GE/cprogram.cc \
		GE/doublestack.cc \
		GE/fparser.cc \
		GE/fpoptimizer.cc \
		GE/population.cc \
		GE/program.cc \
		GE/rule.cc \
		GE/symbol.cc \
		GE/integeranneal.cpp \
		METHODS/adam.cpp \
		METHODS/armadillo1.cpp \
		METHODS/ipso.cpp \
		METHODS/lbfgs.cpp \
		METHODS/neldermead.cpp \
		METHODS/neuralminimizer.cpp \
		METHODS/parallelde.cpp \
		METHODS/parallelpso.cpp \
		METHODS/simanmethod.cpp \
		METHODS/usermethod.cpp \
		MLMODELS/gdfmodel.cpp \
		MLMODELS/mlpproblem.cpp \
		MLMODELS/model.cpp \
		LINESEARCH/armijosearch.cpp \
		LINESEARCH/fibonaccisearch.cpp \
		LINESEARCH/goldensearch.cpp \
		METHODS/bfgs.cpp \
		METHODS/differentialevolution.cpp \
		METHODS/genetic.cpp \
		METHODS/gradientdescent.cpp \
		LINESEARCH/linesearch.cpp \
		METHODS/multistart.cpp \
		MLMODELS/rbfproblem.cpp \
		OPTIMUS/parameterlist.cpp \
		OPTIMUS/statistics.cpp \
		OPTIMUS/collection.cpp \
		OPTIMUS/doublebox.cpp \
		OPTIMUS/similarity.cpp \
		PROBLEMS/bf1.cpp \
		PROBLEMS/bf2.cpp \
		PROBLEMS/branin.cpp \
		PROBLEMS/camel.cpp \
		PROBLEMS/cm.cpp \
		PROBLEMS/diffpower.cpp \
		PROBLEMS/diracproblem.cpp \
		PROBLEMS/easom.cpp \
		PROBLEMS/elp.cpp \
		PROBLEMS/exp.cpp \
		PROBLEMS/fuch1.cpp \
		PROBLEMS/fuchss.cpp \
		PROBLEMS/gkls.cpp \
		PROBLEMS/gkls2100.cpp \
		PROBLEMS/gkls250.cpp \
		PROBLEMS/gkls350.cpp \
		PROBLEMS/goldstein.cpp \
		PROBLEMS/griewank10.cpp \
		PROBLEMS/griewank2.cpp \
		PROBLEMS/hansen.cpp \
		PROBLEMS/hartman3.cpp \
		PROBLEMS/hartman6.cpp \
		PROBLEMS/hess.cpp \
		PROBLEMS/levy.cpp \
		PROBLEMS/potential.cpp \
		PROBLEMS/rosenbrock.cpp \
		PROBLEMS/salkin.cpp \
		PROBLEMS/shekel10.cpp \
		PROBLEMS/shekel5.cpp \
		PROBLEMS/gross.cpp \
		PROBLEMS/shekel7.cpp \
		PROBLEMS/sinu.cpp \
		PROBLEMS/test30n.cpp \
		MLMODELS/dataset.cpp \
		PROBLEMS/userproblem.cpp \
		SAMPLER/kmeanssampler.cpp \
		SAMPLER/maxwellsampler.cpp \
		SAMPLER/neuralsampler.cpp \
		SAMPLER/rbfsampler.cpp \
		SAMPLER/triangularsampler.cpp \
		SAMPLER/uniformsampler.cpp \
		main.cpp \
		OPTIMUS/optimizer.cpp \
		OPTIMUS/parameter.cpp \
		OPTIMUS/problem.cpp \
		PROBLEMS/rastriginproblem.cpp \
		PROBLEMS/test2nproblem.cpp \
		SAMPLER/problemsampler.cpp 
OBJECTS       = cprogram.o \
		doublestack.o \
		fparser.o \
		fpoptimizer.o \
		population.o \
		program.o \
		rule.o \
		symbol.o \
		integeranneal.o \
		adam.o \
		armadillo1.o \
		ipso.o \
		lbfgs.o \
		neldermead.o \
		neuralminimizer.o \
		parallelde.o \
		parallelpso.o \
		simanmethod.o \
		usermethod.o \
		gdfmodel.o \
		mlpproblem.o \
		model.o \
		armijosearch.o \
		fibonaccisearch.o \
		goldensearch.o \
		bfgs.o \
		differentialevolution.o \
		genetic.o \
		gradientdescent.o \
		linesearch.o \
		multistart.o \
		rbfproblem.o \
		parameterlist.o \
		statistics.o \
		collection.o \
		doublebox.o \
		similarity.o \
		bf1.o \
		bf2.o \
		branin.o \
		camel.o \
		cm.o \
		diffpower.o \
		diracproblem.o \
		easom.o \
		elp.o \
		exp.o \
		fuch1.o \
		fuchss.o \
		gkls.o \
		gkls2100.o \
		gkls250.o \
		gkls350.o \
		goldstein.o \
		griewank10.o \
		griewank2.o \
		hansen.o \
		hartman3.o \
		hartman6.o \
		hess.o \
		levy.o \
		potential.o \
		rosenbrock.o \
		salkin.o \
		shekel10.o \
		shekel5.o \
		gross.o \
		shekel7.o \
		sinu.o \
		test30n.o \
		dataset.o \
		userproblem.o \
		kmeanssampler.o \
		maxwellsampler.o \
		neuralsampler.o \
		rbfsampler.o \
		triangularsampler.o \
		uniformsampler.o \
		main.o \
		optimizer.o \
		parameter.o \
		problem.o \
		rastriginproblem.o \
		test2nproblem.o \
		problemsampler.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		GlobalOptimus.pro GE/cprogram.h \
		GE/doublestack.h \
		GE/fparser.hh \
		GE/fpconfig.hh \
		GE/fptypes.hh \
		GE/population.h \
		GE/program.h \
		GE/rule.h \
		GE/symbol.h \
		GE/integeranneal.h \
		METHODS/adam.h \
		METHODS/ipso.h \
		METHODS/lbfgs.h \
		METHODS/neldermead.h \
		METHODS/neuralminimizer.h \
		METHODS/parallelde.h \
		METHODS/parallelpso.h \
		METHODS/simanmethod.h \
		METHODS/usermethod.h \
		METHODS/armadillo1.h \
		MLMODELS/gdfmodel.h \
		MLMODELS/mlpproblem.h \
		MLMODELS/model.h \
		LINESEARCH/armijosearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/linesearch.h \
		METHODS/bfgs.h \
		METHODS/differentialevolution.h \
		METHODS/genetic.h \
		METHODS/gradientdescent.h \
		METHODS/multistart.h \
		MLMODELS/rbfproblem.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/statistics.h \
		OPTIMUS/collection.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/problem.h \
		OPTIMUS/similarity.h \
		PROBLEMS/bf1.h \
		PROBLEMS/bf2.h \
		PROBLEMS/branin.h \
		PROBLEMS/camel.h \
		PROBLEMS/cm.h \
		PROBLEMS/diffpower.h \
		PROBLEMS/diracproblem.h \
		PROBLEMS/easom.h \
		PROBLEMS/elp.h \
		PROBLEMS/exp.h \
		PROBLEMS/fuch1.h \
		PROBLEMS/fuchss.h \
		PROBLEMS/gkls.h \
		PROBLEMS/gkls2100.h \
		PROBLEMS/gkls250.h \
		PROBLEMS/gkls350.h \
		PROBLEMS/gross.h \
		PROBLEMS/goldstein.h \
		PROBLEMS/griewank10.h \
		PROBLEMS/griewank2.h \
		PROBLEMS/hansen.h \
		PROBLEMS/hartman3.h \
		PROBLEMS/hartman6.h \
		PROBLEMS/hess.h \
		PROBLEMS/levy.h \
		PROBLEMS/potential.h \
		PROBLEMS/rastriginproblem.h \
		PROBLEMS/rosenbrock.h \
		PROBLEMS/salkin.h \
		PROBLEMS/shekel10.h \
		PROBLEMS/shekel5.h \
		PROBLEMS/shekel7.h \
		PROBLEMS/sinu.h \
		PROBLEMS/test2nproblem.h \
		PROBLEMS/test30n.h \
		MLMODELS/dataset.h \
		PROBLEMS/userproblem.h \
		SAMPLER/kmeanssampler.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h GE/cprogram.cc \
		GE/doublestack.cc \
		GE/fparser.cc \
		GE/fpoptimizer.cc \
		GE/population.cc \
		GE/program.cc \
		GE/rule.cc \
		GE/symbol.cc \
		GE/integeranneal.cpp \
		METHODS/adam.cpp \
		METHODS/armadillo1.cpp \
		METHODS/ipso.cpp \
		METHODS/lbfgs.cpp \
		METHODS/neldermead.cpp \
		METHODS/neuralminimizer.cpp \
		METHODS/parallelde.cpp \
		METHODS/parallelpso.cpp \
		METHODS/simanmethod.cpp \
		METHODS/usermethod.cpp \
		MLMODELS/gdfmodel.cpp \
		MLMODELS/mlpproblem.cpp \
		MLMODELS/model.cpp \
		LINESEARCH/armijosearch.cpp \
		LINESEARCH/fibonaccisearch.cpp \
		LINESEARCH/goldensearch.cpp \
		METHODS/bfgs.cpp \
		METHODS/differentialevolution.cpp \
		METHODS/genetic.cpp \
		METHODS/gradientdescent.cpp \
		LINESEARCH/linesearch.cpp \
		METHODS/multistart.cpp \
		MLMODELS/rbfproblem.cpp \
		OPTIMUS/parameterlist.cpp \
		OPTIMUS/statistics.cpp \
		OPTIMUS/collection.cpp \
		OPTIMUS/doublebox.cpp \
		OPTIMUS/similarity.cpp \
		PROBLEMS/bf1.cpp \
		PROBLEMS/bf2.cpp \
		PROBLEMS/branin.cpp \
		PROBLEMS/camel.cpp \
		PROBLEMS/cm.cpp \
		PROBLEMS/diffpower.cpp \
		PROBLEMS/diracproblem.cpp \
		PROBLEMS/easom.cpp \
		PROBLEMS/elp.cpp \
		PROBLEMS/exp.cpp \
		PROBLEMS/fuch1.cpp \
		PROBLEMS/fuchss.cpp \
		PROBLEMS/gkls.cpp \
		PROBLEMS/gkls2100.cpp \
		PROBLEMS/gkls250.cpp \
		PROBLEMS/gkls350.cpp \
		PROBLEMS/goldstein.cpp \
		PROBLEMS/griewank10.cpp \
		PROBLEMS/griewank2.cpp \
		PROBLEMS/hansen.cpp \
		PROBLEMS/hartman3.cpp \
		PROBLEMS/hartman6.cpp \
		PROBLEMS/hess.cpp \
		PROBLEMS/levy.cpp \
		PROBLEMS/potential.cpp \
		PROBLEMS/rosenbrock.cpp \
		PROBLEMS/salkin.cpp \
		PROBLEMS/shekel10.cpp \
		PROBLEMS/shekel5.cpp \
		PROBLEMS/gross.cpp \
		PROBLEMS/shekel7.cpp \
		PROBLEMS/sinu.cpp \
		PROBLEMS/test30n.cpp \
		MLMODELS/dataset.cpp \
		PROBLEMS/userproblem.cpp \
		SAMPLER/kmeanssampler.cpp \
		SAMPLER/maxwellsampler.cpp \
		SAMPLER/neuralsampler.cpp \
		SAMPLER/rbfsampler.cpp \
		SAMPLER/triangularsampler.cpp \
		SAMPLER/uniformsampler.cpp \
		main.cpp \
		OPTIMUS/optimizer.cpp \
		OPTIMUS/parameter.cpp \
		OPTIMUS/problem.cpp \
		PROBLEMS/rastriginproblem.cpp \
		PROBLEMS/test2nproblem.cpp \
		SAMPLER/problemsampler.cpp
QMAKE_TARGET  = GlobalOptimus
DESTDIR       = 
TARGET        = GlobalOptimus


first: all
####### Build rules

GlobalOptimus:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GlobalOptimus.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		GlobalOptimus.pro
	$(QMAKE) -o Makefile GlobalOptimus.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
GlobalOptimus.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile GlobalOptimus.pro

qmake_all: FORCE


all: Makefile GlobalOptimus

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents GE/cprogram.h GE/doublestack.h GE/fparser.hh GE/fpconfig.hh GE/fptypes.hh GE/population.h GE/program.h GE/rule.h GE/symbol.h GE/integeranneal.h METHODS/adam.h METHODS/ipso.h METHODS/lbfgs.h METHODS/neldermead.h METHODS/neuralminimizer.h METHODS/parallelde.h METHODS/parallelpso.h METHODS/simanmethod.h METHODS/usermethod.h METHODS/armadillo1.h MLMODELS/gdfmodel.h MLMODELS/mlpproblem.h MLMODELS/model.h LINESEARCH/armijosearch.h LINESEARCH/fibonaccisearch.h LINESEARCH/goldensearch.h LINESEARCH/linesearch.h METHODS/bfgs.h METHODS/differentialevolution.h METHODS/genetic.h METHODS/gradientdescent.h METHODS/multistart.h MLMODELS/rbfproblem.h OPTIMUS/parameterlist.h OPTIMUS/statistics.h OPTIMUS/collection.h OPTIMUS/doublebox.h OPTIMUS/optimizer.h OPTIMUS/parameter.h OPTIMUS/problem.h OPTIMUS/similarity.h PROBLEMS/bf1.h PROBLEMS/bf2.h PROBLEMS/branin.h PROBLEMS/camel.h PROBLEMS/cm.h PROBLEMS/diffpower.h PROBLEMS/diracproblem.h PROBLEMS/easom.h PROBLEMS/elp.h PROBLEMS/exp.h PROBLEMS/fuch1.h PROBLEMS/fuchss.h PROBLEMS/gkls.h PROBLEMS/gkls2100.h PROBLEMS/gkls250.h PROBLEMS/gkls350.h PROBLEMS/gross.h PROBLEMS/goldstein.h PROBLEMS/griewank10.h PROBLEMS/griewank2.h PROBLEMS/hansen.h PROBLEMS/hartman3.h PROBLEMS/hartman6.h PROBLEMS/hess.h PROBLEMS/levy.h PROBLEMS/potential.h PROBLEMS/rastriginproblem.h PROBLEMS/rosenbrock.h PROBLEMS/salkin.h PROBLEMS/shekel10.h PROBLEMS/shekel5.h PROBLEMS/shekel7.h PROBLEMS/sinu.h PROBLEMS/test2nproblem.h PROBLEMS/test30n.h MLMODELS/dataset.h PROBLEMS/userproblem.h SAMPLER/kmeanssampler.h SAMPLER/maxwellsampler.h SAMPLER/neuralsampler.h SAMPLER/problemsampler.h SAMPLER/rbfsampler.h SAMPLER/triangularsampler.h SAMPLER/uniformsampler.h $(DISTDIR)/
	$(COPY_FILE) --parents GE/cprogram.cc GE/doublestack.cc GE/fparser.cc GE/fpoptimizer.cc GE/population.cc GE/program.cc GE/rule.cc GE/symbol.cc GE/integeranneal.cpp METHODS/adam.cpp METHODS/armadillo1.cpp METHODS/ipso.cpp METHODS/lbfgs.cpp METHODS/neldermead.cpp METHODS/neuralminimizer.cpp METHODS/parallelde.cpp METHODS/parallelpso.cpp METHODS/simanmethod.cpp METHODS/usermethod.cpp MLMODELS/gdfmodel.cpp MLMODELS/mlpproblem.cpp MLMODELS/model.cpp LINESEARCH/armijosearch.cpp LINESEARCH/fibonaccisearch.cpp LINESEARCH/goldensearch.cpp METHODS/bfgs.cpp METHODS/differentialevolution.cpp METHODS/genetic.cpp METHODS/gradientdescent.cpp LINESEARCH/linesearch.cpp METHODS/multistart.cpp MLMODELS/rbfproblem.cpp OPTIMUS/parameterlist.cpp OPTIMUS/statistics.cpp OPTIMUS/collection.cpp OPTIMUS/doublebox.cpp OPTIMUS/similarity.cpp PROBLEMS/bf1.cpp PROBLEMS/bf2.cpp PROBLEMS/branin.cpp PROBLEMS/camel.cpp PROBLEMS/cm.cpp PROBLEMS/diffpower.cpp PROBLEMS/diracproblem.cpp PROBLEMS/easom.cpp PROBLEMS/elp.cpp PROBLEMS/exp.cpp PROBLEMS/fuch1.cpp PROBLEMS/fuchss.cpp PROBLEMS/gkls.cpp PROBLEMS/gkls2100.cpp PROBLEMS/gkls250.cpp PROBLEMS/gkls350.cpp PROBLEMS/goldstein.cpp PROBLEMS/griewank10.cpp PROBLEMS/griewank2.cpp PROBLEMS/hansen.cpp PROBLEMS/hartman3.cpp PROBLEMS/hartman6.cpp PROBLEMS/hess.cpp PROBLEMS/levy.cpp PROBLEMS/potential.cpp PROBLEMS/rosenbrock.cpp PROBLEMS/salkin.cpp PROBLEMS/shekel10.cpp PROBLEMS/shekel5.cpp PROBLEMS/gross.cpp PROBLEMS/shekel7.cpp PROBLEMS/sinu.cpp PROBLEMS/test30n.cpp MLMODELS/dataset.cpp PROBLEMS/userproblem.cpp SAMPLER/kmeanssampler.cpp SAMPLER/maxwellsampler.cpp SAMPLER/neuralsampler.cpp SAMPLER/rbfsampler.cpp SAMPLER/triangularsampler.cpp SAMPLER/uniformsampler.cpp main.cpp OPTIMUS/optimizer.cpp OPTIMUS/parameter.cpp OPTIMUS/problem.cpp PROBLEMS/rastriginproblem.cpp PROBLEMS/test2nproblem.cpp SAMPLER/problemsampler.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O3 -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -O2 -O3 -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

cprogram.o: GE/cprogram.cc GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		GE/program.h \
		MLMODELS/model.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cprogram.o GE/cprogram.cc

doublestack.o: GE/doublestack.cc GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doublestack.o GE/doublestack.cc

fparser.o: GE/fparser.cc GE/fparser.hh \
		GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fparser.o GE/fparser.cc

fpoptimizer.o: GE/fpoptimizer.cc GE/fpconfig.hh \
		GE/fparser.hh \
		GE/fptypes.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fpoptimizer.o GE/fpoptimizer.cc

population.o: GE/population.cc GE/population.h \
		GE/program.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		OPTIMUS/problem.h \
		METHODS/bfgs.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		METHODS/simanmethod.h \
		OPTIMUS/collection.h \
		GE/integeranneal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o population.o GE/population.cc

program.o: GE/program.cc GE/program.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o program.o GE/program.cc

rule.o: GE/rule.cc GE/rule.h \
		GE/symbol.h \
		GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rule.o GE/rule.cc

symbol.o: GE/symbol.cc GE/symbol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o symbol.o GE/symbol.cc

integeranneal.o: GE/integeranneal.cpp GE/integeranneal.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		GE/program.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integeranneal.o GE/integeranneal.cpp

adam.o: METHODS/adam.cpp METHODS/adam.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/armijosearch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adam.o METHODS/adam.cpp

armadillo1.o: METHODS/armadillo1.cpp METHODS/armadillo1.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armadillo1.o METHODS/armadillo1.cpp

ipso.o: METHODS/ipso.cpp METHODS/ipso.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ipso.o METHODS/ipso.cpp

lbfgs.o: METHODS/lbfgs.cpp METHODS/lbfgs.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lbfgs.o METHODS/lbfgs.cpp

neldermead.o: METHODS/neldermead.cpp METHODS/neldermead.h \
		OPTIMUS/problem.h \
		OPTIMUS/collection.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neldermead.o METHODS/neldermead.cpp

neuralminimizer.o: METHODS/neuralminimizer.cpp METHODS/neuralminimizer.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neuralminimizer.o METHODS/neuralminimizer.cpp

parallelde.o: METHODS/parallelde.cpp METHODS/parallelde.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parallelde.o METHODS/parallelde.cpp

parallelpso.o: METHODS/parallelpso.cpp METHODS/parallelpso.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parallelpso.o METHODS/parallelpso.cpp

simanmethod.o: METHODS/simanmethod.cpp METHODS/simanmethod.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simanmethod.o METHODS/simanmethod.cpp

usermethod.o: METHODS/usermethod.cpp METHODS/usermethod.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usermethod.o METHODS/usermethod.cpp

gdfmodel.o: MLMODELS/gdfmodel.cpp MLMODELS/gdfmodel.h \
		MLMODELS/model.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		GE/program.h \
		GE/population.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gdfmodel.o MLMODELS/gdfmodel.cpp

mlpproblem.o: MLMODELS/mlpproblem.cpp MLMODELS/mlpproblem.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		MLMODELS/model.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mlpproblem.o MLMODELS/mlpproblem.cpp

model.o: MLMODELS/model.cpp MLMODELS/model.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o MLMODELS/model.cpp

armijosearch.o: LINESEARCH/armijosearch.cpp LINESEARCH/armijosearch.h \
		LINESEARCH/linesearch.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armijosearch.o LINESEARCH/armijosearch.cpp

fibonaccisearch.o: LINESEARCH/fibonaccisearch.cpp LINESEARCH/fibonaccisearch.h \
		LINESEARCH/linesearch.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fibonaccisearch.o LINESEARCH/fibonaccisearch.cpp

goldensearch.o: LINESEARCH/goldensearch.cpp LINESEARCH/goldensearch.h \
		LINESEARCH/linesearch.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o goldensearch.o LINESEARCH/goldensearch.cpp

bfgs.o: METHODS/bfgs.cpp METHODS/bfgs.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bfgs.o METHODS/bfgs.cpp

differentialevolution.o: METHODS/differentialevolution.cpp METHODS/differentialevolution.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o differentialevolution.o METHODS/differentialevolution.cpp

genetic.o: METHODS/genetic.cpp METHODS/genetic.h \
		OPTIMUS/collection.h \
		OPTIMUS/problem.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o genetic.o METHODS/genetic.cpp

gradientdescent.o: METHODS/gradientdescent.cpp METHODS/gradientdescent.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/armijosearch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gradientdescent.o METHODS/gradientdescent.cpp

linesearch.o: LINESEARCH/linesearch.cpp LINESEARCH/linesearch.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linesearch.o LINESEARCH/linesearch.cpp

multistart.o: METHODS/multistart.cpp METHODS/multistart.h \
		OPTIMUS/problem.h \
		OPTIMUS/collection.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multistart.o METHODS/multistart.cpp

rbfproblem.o: MLMODELS/rbfproblem.cpp MLMODELS/rbfproblem.h \
		MLMODELS/dataset.h \
		OPTIMUS/problem.h \
		MLMODELS/model.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rbfproblem.o MLMODELS/rbfproblem.cpp

parameterlist.o: OPTIMUS/parameterlist.cpp OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameterlist.o OPTIMUS/parameterlist.cpp

statistics.o: OPTIMUS/statistics.cpp OPTIMUS/statistics.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statistics.o OPTIMUS/statistics.cpp

collection.o: OPTIMUS/collection.cpp OPTIMUS/collection.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o collection.o OPTIMUS/collection.cpp

doublebox.o: OPTIMUS/doublebox.cpp OPTIMUS/doublebox.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doublebox.o OPTIMUS/doublebox.cpp

similarity.o: OPTIMUS/similarity.cpp OPTIMUS/similarity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o similarity.o OPTIMUS/similarity.cpp

bf1.o: PROBLEMS/bf1.cpp PROBLEMS/bf1.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bf1.o PROBLEMS/bf1.cpp

bf2.o: PROBLEMS/bf2.cpp PROBLEMS/bf2.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bf2.o PROBLEMS/bf2.cpp

branin.o: PROBLEMS/branin.cpp PROBLEMS/branin.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o branin.o PROBLEMS/branin.cpp

camel.o: PROBLEMS/camel.cpp PROBLEMS/camel.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camel.o PROBLEMS/camel.cpp

cm.o: PROBLEMS/cm.cpp PROBLEMS/cm.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cm.o PROBLEMS/cm.cpp

diffpower.o: PROBLEMS/diffpower.cpp PROBLEMS/diffpower.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diffpower.o PROBLEMS/diffpower.cpp

diracproblem.o: PROBLEMS/diracproblem.cpp PROBLEMS/diracproblem.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diracproblem.o PROBLEMS/diracproblem.cpp

easom.o: PROBLEMS/easom.cpp PROBLEMS/easom.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o easom.o PROBLEMS/easom.cpp

elp.o: PROBLEMS/elp.cpp PROBLEMS/elp.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o elp.o PROBLEMS/elp.cpp

exp.o: PROBLEMS/exp.cpp PROBLEMS/exp.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exp.o PROBLEMS/exp.cpp

fuch1.o: PROBLEMS/fuch1.cpp PROBLEMS/fuch1.h \
		OPTIMUS/problem.h \
		MLMODELS/mlpproblem.h \
		MLMODELS/dataset.h \
		MLMODELS/model.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fuch1.o PROBLEMS/fuch1.cpp

fuchss.o: PROBLEMS/fuchss.cpp PROBLEMS/fuchss.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fuchss.o PROBLEMS/fuchss.cpp

gkls.o: PROBLEMS/gkls.cpp PROBLEMS/gkls.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gkls.o PROBLEMS/gkls.cpp

gkls2100.o: PROBLEMS/gkls2100.cpp PROBLEMS/gkls2100.h \
		OPTIMUS/problem.h \
		PROBLEMS/gkls.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gkls2100.o PROBLEMS/gkls2100.cpp

gkls250.o: PROBLEMS/gkls250.cpp PROBLEMS/gkls250.h \
		OPTIMUS/problem.h \
		PROBLEMS/gkls.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gkls250.o PROBLEMS/gkls250.cpp

gkls350.o: PROBLEMS/gkls350.cpp PROBLEMS/gkls350.h \
		OPTIMUS/problem.h \
		PROBLEMS/gkls.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gkls350.o PROBLEMS/gkls350.cpp

goldstein.o: PROBLEMS/goldstein.cpp PROBLEMS/goldstein.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o goldstein.o PROBLEMS/goldstein.cpp

griewank10.o: PROBLEMS/griewank10.cpp PROBLEMS/griewank10.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o griewank10.o PROBLEMS/griewank10.cpp

griewank2.o: PROBLEMS/griewank2.cpp PROBLEMS/griewank2.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o griewank2.o PROBLEMS/griewank2.cpp

hansen.o: PROBLEMS/hansen.cpp PROBLEMS/hansen.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hansen.o PROBLEMS/hansen.cpp

hartman3.o: PROBLEMS/hartman3.cpp PROBLEMS/hartman3.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hartman3.o PROBLEMS/hartman3.cpp

hartman6.o: PROBLEMS/hartman6.cpp PROBLEMS/hartman6.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hartman6.o PROBLEMS/hartman6.cpp

hess.o: PROBLEMS/hess.cpp PROBLEMS/hess.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hess.o PROBLEMS/hess.cpp

levy.o: PROBLEMS/levy.cpp PROBLEMS/levy.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o levy.o PROBLEMS/levy.cpp

potential.o: PROBLEMS/potential.cpp PROBLEMS/potential.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o potential.o PROBLEMS/potential.cpp

rosenbrock.o: PROBLEMS/rosenbrock.cpp PROBLEMS/rosenbrock.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rosenbrock.o PROBLEMS/rosenbrock.cpp

salkin.o: PROBLEMS/salkin.cpp PROBLEMS/salkin.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o salkin.o PROBLEMS/salkin.cpp

shekel10.o: PROBLEMS/shekel10.cpp PROBLEMS/shekel10.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shekel10.o PROBLEMS/shekel10.cpp

shekel5.o: PROBLEMS/shekel5.cpp PROBLEMS/shekel5.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shekel5.o PROBLEMS/shekel5.cpp

gross.o: PROBLEMS/gross.cpp PROBLEMS/fuch1.h \
		OPTIMUS/problem.h \
		MLMODELS/mlpproblem.h \
		MLMODELS/dataset.h \
		MLMODELS/model.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gross.o PROBLEMS/gross.cpp

shekel7.o: PROBLEMS/shekel7.cpp PROBLEMS/shekel7.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shekel7.o PROBLEMS/shekel7.cpp

sinu.o: PROBLEMS/sinu.cpp PROBLEMS/sinu.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sinu.o PROBLEMS/sinu.cpp

test30n.o: PROBLEMS/test30n.cpp PROBLEMS/test30n.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test30n.o PROBLEMS/test30n.cpp

dataset.o: MLMODELS/dataset.cpp MLMODELS/dataset.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dataset.o MLMODELS/dataset.cpp

userproblem.o: PROBLEMS/userproblem.cpp PROBLEMS/userproblem.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userproblem.o PROBLEMS/userproblem.cpp

kmeanssampler.o: SAMPLER/kmeanssampler.cpp SAMPLER/kmeanssampler.h \
		SAMPLER/problemsampler.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kmeanssampler.o SAMPLER/kmeanssampler.cpp

maxwellsampler.o: SAMPLER/maxwellsampler.cpp SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxwellsampler.o SAMPLER/maxwellsampler.cpp

neuralsampler.o: SAMPLER/neuralsampler.cpp SAMPLER/neuralsampler.h \
		SAMPLER/problemsampler.h \
		OPTIMUS/problem.h \
		MLMODELS/dataset.h \
		METHODS/bfgs.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		METHODS/lbfgs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neuralsampler.o SAMPLER/neuralsampler.cpp

rbfsampler.o: SAMPLER/rbfsampler.cpp SAMPLER/rbfsampler.h \
		OPTIMUS/problem.h \
		SAMPLER/problemsampler.h \
		MLMODELS/dataset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rbfsampler.o SAMPLER/rbfsampler.cpp

triangularsampler.o: SAMPLER/triangularsampler.cpp SAMPLER/triangularsampler.h \
		SAMPLER/problemsampler.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o triangularsampler.o SAMPLER/triangularsampler.cpp

uniformsampler.o: SAMPLER/uniformsampler.cpp SAMPLER/uniformsampler.h \
		SAMPLER/problemsampler.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uniformsampler.o SAMPLER/uniformsampler.cpp

main.o: main.cpp PROBLEMS/rastriginproblem.h \
		OPTIMUS/problem.h \
		PROBLEMS/test2nproblem.h \
		PROBLEMS/bf1.h \
		PROBLEMS/bf2.h \
		PROBLEMS/branin.h \
		PROBLEMS/camel.h \
		PROBLEMS/cm.h \
		PROBLEMS/diffpower.h \
		PROBLEMS/easom.h \
		PROBLEMS/elp.h \
		PROBLEMS/exp.h \
		PROBLEMS/gkls250.h \
		PROBLEMS/gkls2100.h \
		PROBLEMS/gkls350.h \
		PROBLEMS/goldstein.h \
		PROBLEMS/griewank2.h \
		PROBLEMS/griewank10.h \
		PROBLEMS/hansen.h \
		PROBLEMS/hartman3.h \
		PROBLEMS/hartman6.h \
		PROBLEMS/potential.h \
		PROBLEMS/rosenbrock.h \
		PROBLEMS/shekel5.h \
		PROBLEMS/shekel7.h \
		PROBLEMS/shekel10.h \
		PROBLEMS/sinu.h \
		PROBLEMS/test30n.h \
		MLMODELS/mlpproblem.h \
		MLMODELS/dataset.h \
		MLMODELS/model.h \
		OPTIMUS/parameterlist.h \
		OPTIMUS/parameter.h \
		MLMODELS/rbfproblem.h \
		PROBLEMS/diracproblem.h \
		PROBLEMS/userproblem.h \
		PROBLEMS/fuchss.h \
		PROBLEMS/levy.h \
		PROBLEMS/salkin.h \
		PROBLEMS/hess.h \
		PROBLEMS/fuch1.h \
		METHODS/gradientdescent.h \
		OPTIMUS/optimizer.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/armijosearch.h \
		METHODS/multistart.h \
		OPTIMUS/collection.h \
		METHODS/genetic.h \
		METHODS/bfgs.h \
		METHODS/lbfgs.h \
		METHODS/differentialevolution.h \
		METHODS/ipso.h \
		METHODS/neuralminimizer.h \
		METHODS/parallelde.h \
		METHODS/parallelpso.h \
		METHODS/neldermead.h \
		METHODS/adam.h \
		METHODS/armadillo1.h \
		METHODS/simanmethod.h \
		METHODS/usermethod.h \
		OPTIMUS/statistics.h \
		MLMODELS/functionalrbf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

optimizer.o: OPTIMUS/optimizer.cpp OPTIMUS/optimizer.h \
		OPTIMUS/problem.h \
		OPTIMUS/parameter.h \
		OPTIMUS/doublebox.h \
		OPTIMUS/similarity.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		METHODS/gradientdescent.h \
		LINESEARCH/linesearch.h \
		LINESEARCH/fibonaccisearch.h \
		LINESEARCH/goldensearch.h \
		LINESEARCH/armijosearch.h \
		METHODS/bfgs.h \
		METHODS/lbfgs.h \
		METHODS/neldermead.h \
		OPTIMUS/collection.h \
		METHODS/adam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optimizer.o OPTIMUS/optimizer.cpp

parameter.o: OPTIMUS/parameter.cpp OPTIMUS/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameter.o OPTIMUS/parameter.cpp

problem.o: OPTIMUS/problem.cpp OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o problem.o OPTIMUS/problem.cpp

rastriginproblem.o: PROBLEMS/rastriginproblem.cpp PROBLEMS/rastriginproblem.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rastriginproblem.o PROBLEMS/rastriginproblem.cpp

test2nproblem.o: PROBLEMS/test2nproblem.cpp PROBLEMS/test2nproblem.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test2nproblem.o PROBLEMS/test2nproblem.cpp

problemsampler.o: SAMPLER/problemsampler.cpp SAMPLER/problemsampler.h \
		OPTIMUS/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o problemsampler.o SAMPLER/problemsampler.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/GlobalOptimus/bin || mkdir -p $(INSTALL_ROOT)/opt/GlobalOptimus/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/GlobalOptimus/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/GlobalOptimus/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/GlobalOptimus/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/GlobalOptimus/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

